### ISSUE TITLE
undefined reference to `rocksdb::Iterator::Iterator()'

### ISSUE THREAD

**Issue by krishnakumarcitrus** [mongodb-partners/mongo-rocks#19]
Trying to build using the version v3.0.5-mongorocks produces this error after compiling for a very long time.

build/linux2/normal/mongo/db/storage/rocks/rocks_recovery_unit.o: In function `RocksIterator':
/opt/mongoRocks03/rocksdb/mongo/src/mongo/db/storage/rocks/rocks_recovery_unit.h:67: undefined reference to`rocksdb::Iterator::Iterator()'
/opt/mongoRocks03/rocksdb/mongo/src/mongo/db/storage/rocks/rocks_recovery_unit.h:67: undefined reference to `rocksdb::Iterator::Iterator()'
collect2: error: ld returned 1 exit status
scons: **\* [build/linux2/normal/mongo/mongod] Error 1
scons: building terminated because of errors.

**Comment by igorcanadi** [comment]
Hey @krishnakumarcitrus, did you get this resolved? This probably means that you didn't install RocksDB correctly.

**Comment by hslorenzo** [comment]
I have the same issue. I just followed this steps:
```
# install compression libraries (zlib, bzip2, snappy):
sudo apt-get install zlib1g-dev; sudo apt-get install libbz2-dev; sudo apt-get install libsnappy-dev
# get rocksdb
git clone https://github.com/facebook/rocksdb.git
# compile rocksdb
cd rocksdb; make static_lib; sudo INSTALL_PATH=/usr make install; cd ..
# get mongo
git clone https://github.com/mongodb/mongo.git
# get mongorocks
git clone https://github.com/mongodb-partners/mongo-rocks
# add rocksdb module to mongo
mkdir -p mongo/src/mongo/db/modules/
ln -sf ~/mongo-rocks mongo/src/mongo/db/modules/rocks
# compile mongo
cd mongo; scons  //---->>>Error here
```
And this is the error I got:

```
scons: Building targets ...
Linking build/opt/mongo/mongod
src/mongo/db/modules/rocks/src/rocks_recovery_unit.h:72: error: undefined reference to 'rocksdb::Iterator::Iterator()'
src/mongo/db/modules/rocks/src/rocks_recovery_unit.h:72: error: undefined reference to 'rocksdb::Iterator::Iterator()'

```

**Comment by krishnakumarcitrus** [comment]
@hslorenzo Yes, the same steps I followed. I've seen other posts too, they say we haven't installed rokcsDB correctly.

All the steps they mentioned for rocksDB installation was followed correctly i guess. Any idea where we might have went wrong?

**Comment by igorcanadi** [comment]
What does `git log` say? This is weird, usually `git clone` checks out the master.
