### ISSUE TITLE
Cannot compile using MongoDB 3.4.0 - 3.4.4

### ISSUE THREAD

**Issue by xxks-kkk** [mongodb-partners/mongo-rocks#141]
We have tried to compile the mongo-rocks by exactly following the steps listed. However, there is an compilation error:

```
In file included from src/mongo/db/modules/rocks/src/rocks_engine.h:52:0,
                 from src/mongo/db/modules/rocks/src/rocks_init.cpp:39:
src/mongo/db/modules/rocks/src/rocks_snapshot_manager.h:62:10: error: 'void mongo::RocksSnapshotManager::setCommittedSnapshot(const mongo::Timestamp&)' marked 'final', but is not virtual
     void setCommittedSnapshot(const Timestamp& ts) final;
          ^
In file included from src/mongo/db/modules/rocks/src/rocks_snapshot_manager.h:34:0,
                 from src/mongo/db/modules/rocks/src/rocks_engine.h:52,
                 from src/mongo/db/modules/rocks/src/rocks_init.cpp:39:
src/mongo/db/storage/snapshot_manager.h:83:18: error: 'virtual void mongo::SnapshotManager::setCommittedSnapshot(const mongo::SnapshotName&)' was hidden [-Werror=overloaded-virtual]
     virtual void setCommittedSnapshot(const SnapshotName& name) = 0;
```

I'm using Ubuntu. 

Thanks much!

**Comment by igorcanadi** [comment]
Hey @xxks-kkk , you need to check out v3.4 branch of MongoRocks: https://github.com/mongodb-partners/mongo-rocks/tree/v3.4

**Comment by xxks-kkk** [comment]
Hello,

Thanks for the tips. I have compiled successfully but I got the following error message when start the MongoDB instance:

```
2018-04-13T15:31:25.813-0500 I CONTROL  [initandlisten] options: { storage: { dbPath: "/u/weisun/vijay-fp/db", engine: "rocksdb" } }
2018-04-13T15:31:25.832-0500 I -        [initandlisten] Invariant failure: s resulted in status InternalError: Invalid argument: Compression type Snappy is not linked with the binary. at src/mongo/db/modules/rocks/src/rocks_engine.cpp 208
```

I have installed libsnappy-dev. Do you know any possible reason for this error?

Thanks!

**Comment by xxks-kkk** [comment]
Hello,

Is there any way to turn off snappy support (i.e., compression) in mongo-rocks?

Thanks!

**Comment by xxks-kkk** [comment]
Thanks! The issue is solved!

**Comment by y123456yz** [comment]
@xxks-kkk xxks-kkk 

which rocksdb version you used, thanks!
I use the newest rocksdb version, I compile failed, thanks again
